---
languages:
- bash
- c
- c++
- cplusplus
- cpp
- crystal
- csharp
- d
- dart
- default
- generic
- haxe
- julia
- r
- ruby
- rust
- sh
- shell
features:
- chromium
- firefox
- google-chrome
- memcached
- mongodb
- phantomjs
- postgresql
- rabbitmq
- redis
- sphinxsearch
- sqlite
- xserver
