inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Style/FileName:
  Exclude:
    - 'run-foodcritic'

Metrics/AbcSize:
  Exclude:
    - 'run-foodcritic'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'run-foodcritic'

Metrics/MethodLength:
  Exclude:
    - 'run-foodcritic'

Metrics/PerceivedComplexity:
  Exclude:
    - 'run-foodcritic'
