language: ruby
dist: trusty
group: edge
sudo: true
cache: bundler
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:${PATH}"
  - REQUEST_INTERVAL=5
  - SPEC_SUITES='travis_ci_minimal,travis_ci_mega'
  - SPEC_ARGS='--tag ~dev'
  - SPEC_RUNNER='bash -lc'
  - SKIP_CHEFDK_REMOVAL='1'
  - PACKER_CHEF_PREFIX="${TRAVIS_BUILD_DIR}/tmp"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- unset GEM_PATH
- bundle install --path vendor/bundle
- ./bin/packer-build-install
- ln -sv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR}/tmp/packer-chef-local"
script:
- make hackcheck
- make
- git diff --exit-code
- git diff --cached --exit-code
- make test
- sudo packer-scripts/run-serverspecs
- make packer-build-trigger
