language: generic
dist: trusty
group: edge
sudo: true
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- mkdir -p tmp
- echo $GCE_ACCOUNT_FILE_B64_BZ2 | base64 -d | bunzip2 > tmp/gce.json
script:
- make hackcheck
- make
- git diff --exit-code
- git diff --cached --exit-code
- env -i HOME=$HOME PATH=$PATH
    bash -l -c 'source .example.env && unset PACKER_LOG && ./runtests'
- make downstreams
