language: generic
dist: trusty
group: edge
sudo: true
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:$PATH"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- unset GEM_PATH
- gem install git
- ./bin/packer-build-install
script:
- make hackcheck
- make
- git diff --exit-code
- git diff --cached --exit-code
- rspec
- ./runtests --env .example.env
- if [[ $TRAVIS_PULL_REQUEST = false ]] ; then
    ./bin/trigger-downstreams ;
  else
    echo '✮✮✮ Skip trigger-downstreams for pull request builds ✮✮✮' ;
  fi
