language: universe
dist: trusty
group: edge
sudo: required
cache:
  bundler: true
  directories:
  - ${HOME}/bin
env:
  matrix:
  - DIST=trusty
    TRAVIS_JOB_BOARD_REGISTER_YML="${TRAVIS_BUILD_DIR}/.example-job-board-register-sugilite.yml"
  global:
  - LANG=en_US.UTF-8
  - NODE_ATTRIBUTES_YML="${TRAVIS_BUILD_DIR}/.example-node-attributes.yml"
  - PACKER_CHEF_PREFIX="${TRAVIS_BUILD_DIR}/tmp"
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:${HOME}/bin:${PATH}"
  - REQUEST_INTERVAL=5
  - SKIP_CHEFDK_REMOVAL='1'
  - SPEC_ARGS='--tag ~dev'
  - SPEC_RUNNER='bash -lc'
  - SPEC_SUITES='travis_packer_templates'
matrix:
  include:
  - language: ruby
    rvm: 2.3.1
    env: DIST=precise
         TRAVIS_JOB_BOARD_REGISTER_YML="${TRAVIS_BUILD_DIR}/.example-job-board-register-standard.yml"
    dist: precise
    group: edge
install:
- rvm use 2.3.1 --install --binary --fuzzy
- bundle install --jobs=3 --retry=2 --path=vendor/bundle
- if ! shellcheck --version ; then
    sudo apt-add-repository "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" ;
    sudo apt-get -qq update ;
    sudo apt-get -t trusty-backports install shellcheck ;
  fi
- ./bin/packer-build-install
- ln -sv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR}/tmp/packer-chef-local"
script:
- make
- git diff --exit-code
- git diff --cached --exit-code
- bundle exec make test
- bundle exec sudo packer-scripts/run-serverspecs
- for f in ~/.*_rspec.json ; do
    echo "checking $f" ;
    jq . < $f &>/dev/null ;
  done
after_success:
- if [[ $TRAVIS_JOB_BOARD_REGISTER_YML =~ sugilite ]] ; then
    git fetch --unshallow ;
    env | grep -E '^(PACKER|TRAVIS|TAGS|IMAGE_NAME)' | grep -v TOKEN | sort ;
    bundle exec make packer-build-trigger ;
  else
    echo 'no packer-build-trigger for you' ;
  fi
