language: ruby
dist: trusty
group: edge
sudo: required
cache:
  bundler: true
  directories:
  - ${HOME}/bin
rvm: 2.3.1
env:
  matrix:
  - SPEC_SUITES='travis_packer_templates,travis_ci_connie,travis_ci_sugilite'
    TRAVIS_JOB_BOARD_REGISTER_YML="${TRAVIS_BUILD_DIR}/.example-job-board-register-sugilite.yml"
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:${HOME}/bin:${PATH}"
  - REQUEST_INTERVAL=5
  - SPEC_ARGS='--tag ~dev'
  - SPEC_RUNNER='bash -lc'
  - SKIP_CHEFDK_REMOVAL='1'
  - PACKER_CHEF_PREFIX="${TRAVIS_BUILD_DIR}/tmp"
matrix:
  include:
  - env: SPEC_SUITES='travis_packer_templates,travis_ci_standard'
         TRAVIS_JOB_BOARD_REGISTER_YML="${TRAVIS_BUILD_DIR}/.example-job-board-register-standard.yml"
    dist: precise
    group: edge
install:
- bundle install --path vendor/bundle
- ./bin/packer-build-install
- ln -sv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR}/tmp/packer-chef-local"
script:
- make
- git diff --exit-code
- git diff --cached --exit-code
- if ! packer version &>/dev/null ; then make install-packer ; fi
- bundle exec make test
- bundle exec sudo packer-scripts/run-serverspecs
- for f in ~/.*_rspec.json ; do echo "checking $f" ; jq . < $f &>/dev/null ; done
- git fetch --unshallow
after_success:
- if [[ $SPEC_SUITES =~ sugilite ]] ; then
    bundle exec make packer-build-trigger ;
  else
    echo 'no packer-build-trigger for you' ;
  fi
