language: universe
dist: trusty
group: edge
sudo: required
filter_secrets: false
cache:
  bundler: true
  directories:
  - ${HOME}/bin
env:
  matrix:
  - DIST=trusty
    TRAVIS_JOB_BOARD_REGISTER_YML="${TRAVIS_BUILD_DIR}/.example-job-board-register-sugilite.yml"
  global:
  - DPKG_MANIFEST_JSON="${TRAVIS_BUILD_DIR}/.example-dpkg-manifest.json"
  - LANG=en_US.UTF-8
  - NODE_ATTRIBUTES_YML="${TRAVIS_BUILD_DIR}/.example-node-attributes.yml"
  - PACKER_CHEF_PREFIX="${TRAVIS_BUILD_DIR}/tmp"
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:${HOME}/bin:${PATH}"
  - REQUEST_INTERVAL=5
  - SHELLCHECK_URL="https://s3.amazonaws.com/travis-blue-public/binaries/ubuntu/14.04/x86_64/shellcheck-0.4.5.tar.bz2"
  - SHFMT_URL="https://github.com/mvdan/sh/releases/download/v0.6.0/shfmt_v0.6.0_linux_amd64"
  - SKIP_CHEFDK_REMOVAL='1'
  - SPEC_ARGS='--tag ~dev'
  - SPEC_RUNNER='bash -lc'
  - SPEC_SUITES='travis_packer_templates'
  - SYSTEM_INFO_JSON="${TRAVIS_BUILD_DIR}/.example_system_info.json"
install:
- if [[ -f .test-branch ]]; then
    export TRAVIS_COOKBOOKS_TEST_BRANCH="$(cat .test-branch 2>/dev/null)";
  fi
- rvm use 2.4.1 --install --binary --fuzzy
- bundle install --jobs=3 --retry=2 --path=vendor/bundle
- if ! shellcheck --version &>/dev/null; then
    curl -sSL "${SHELLCHECK_URL}"
    | tar --exclude 'SHA256SUMS' --strip-components=1 -C "${HOME}/bin" -xjf -;
  fi
- shellcheck --version
- if ! command -v shfmt; then
    curl -sSL "${SHFMT_URL}" -o "${HOME}/bin/shfmt";
    chmod +x "${HOME}/bin/shfmt";
  fi
- ./bin/packer-build-install
- ln -sv "${TRAVIS_BUILD_DIR}" "${TRAVIS_BUILD_DIR}/tmp/packer-chef-local"

script:
- make
- bundle exec make test
- git diff --exit-code
- git diff --cached --exit-code
- travis_retry bundle exec bash -xc 'sudo packer-scripts/run-serverspecs'
- for f in ~/.*_rspec.json; do
    echo "checking $f";
    jq . < $f &>/dev/null;
  done
after_success:
- if [[ $TRAVIS_JOB_BOARD_REGISTER_YML =~ sugilite ]]; then
    git fetch --unshallow;
    bundle exec make packer-build-trigger;
  else
    echo 'no packer-build-trigger for you';
  fi
