language: generic
dist: trusty
group: edge
sudo: true
cache: bundler
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:$PATH"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- unset GEM_PATH
- bundle install --path vendor/bundle
- ./bin/packer-build-install
script:
- make hackcheck
- make
- git diff --exit-code
- git diff --cached --exit-code
- make test
- make packer-build-trigger
