language: generic
dist: trusty
sudo: true
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:/usr/local/packer:$PATH"
  - PACKER_VERSION="0.10.1"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- curl -sSL -o packer.zip  "https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip"
- sudo unzip packer.zip -d /usr/local/packer
- mkdir -p tmp
- echo $GCE_ACCOUNT_FILE_B64_BZ2 | base64 -d | bunzip2 > tmp/gce.json
script:
- make hackcheck
- make
- git diff --exit-code
- git diff --cached --exit-code
- env -i HOME=$HOME PATH=$PATH
    bash -l -c 'source .example.env && unset PACKER_LOG && ./runtests'
- make downstreams
