language: generic
dist: trusty
group: edge
sudo: true
env:
  global:
  - PATH="/opt/chefdk/bin:/opt/chefdk/embedded/bin:/opt/chef/bin:$PATH"
addons:
  apt:
    sources:
    - chef-stable-trusty
    packages:
    - chefdk
install:
- unset GEM_PATH
- mkdir -p tmp
- echo $GCE_ACCOUNT_FILE_B64_BZ2 | base64 -d | bunzip2 > tmp/gce.json
script:
- make hackcheck
- make
- git diff --exit-code
- git diff --cached --exit-code
- rspec
- env -i HOME=$HOME PATH=$PATH
    bash -l -c 'source .example.env && unset PACKER_LOG && ./runtests'
- ./bin/trigger-downstreams
