#!/bin/csh
pkg install -y bash

#pkg install -y python36
#pkg install -y python37
#pkg install -y python38
#ln -s /usr/local/bin/python3.8 /usr/local/bin/python
#pkg install -y pypy
#pkg install -y pypy3
#pkg install -y py27-pip
#pkg install -y py37-pip
#pip install --upgrade pip
